### PR TITLE
Add recognition styles for code in post

### PR DESCRIPTION
**Pull request by mmmm1998**

### CODE REVIEW

**Comment by iamwavecut** [comment]
@mmmm1998 add these changes to source.styl as well.

**Comment by mmmm1998** [comment]
I added, but I am not sure, that I have done all correctly

**Comment by mmmm1998** [comment]
Well, what about this pull request?

**Comment by iamwavecut** [comment]
I had some concerns on it but i'll back to it asap

**Comment by mmmm1998** [comment]
Looks outdated

**Pull request closed without merging**
